name: docker_publish

on:
  push:
    branches:
      - 'f/ci'
    tags:
      - 'v*.*.*'

jobs:
  docker_pipeline:
    uses: babylonlabs-io/.github/.github/workflows/reusable_docker_pipeline.yml@v0.3.1
    secrets: inherit
    with:
      publish: true
